# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019-2020 kenzo <kenzok8@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Argon Dark by kenzo
LUCI_DEPENDS:=
PKG_VERSION:=2.0
PKG_RELEASE:=02-20200709

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
