# LuCI Material Theme
# Copyright 2015 Lutty Yang <lutty@wcan.in>
#
# Licensed under the Apache License v2.0
# http://www.apache.org/licenses/LICENSE-2.0

include $(TOPDIR)/rules.mk

THEME_NAME:=Opentomcat
THEME_TITLE:=Opentomcat

PKG_NAME:=luci-theme-$(THEME_NAME)
PKG_VERSION:=0.3.5

PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

include $(TOPDIR)/feeds/luci/luci.mk
