# LuCI Material Theme
# Copyright 2015 Lutty Yang <lutty@wcan.in>
#
# Licensed under the Apache License v2.0
# http://www.apache.org/licenses/LICENSE-2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Opentomcat Theme
LUCI_DEPENDS:=
PKG_VERSION:=1.0.0
PKG_RELEASE:=20201005

include $(TOPDIR)/feeds/luci/luci.mk
