# Copyright (C) 2008-2019 Jerrykuku
# Copyright (C) 2019-2020 sirpdboy
# https://github.com/Myoko/openwrt-packages
# This is free software, licensed under the Apache License, Version 2.0 .
#


include $(TOPDIR)/rules.mk

THEME_NAME:=Opentomcat
THEME_TITLE:=Opentomcat Theme

PKG_NAME:=luci-theme-$(THEME_NAME)
PKG_VERSION:=1.0.0
PKG_RELEASE:=20201005


include $(INCLUDE_DIR)/package.mk

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
